language: php

php:
  - 5.6
  - 7.0
  - 7.1

sudo: false

before_install:
  - composer self-update

install:
  - travis_retry make build-dependencies

script:
  - make test-phpunit-53
  - make test-phpunit-54
  - make test-phpunit-55

notifications:
  email: false
